cnames.AB03 <- c("Mag", "Rrup", "Prd", "ftype", "depth", "Sc", "Sd", "Se")
cnames.AC10 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30")
cnames.AGA16.tw.C01 <- c("Mag", "Rrup", "Prd", "ftype", "Vs30", "Ztor", "depth", "Rhypo")
cnames.AGA16.tw.F10 <- c("Mag", "Rrup", "Prd", "ftype", "Vs30", "Ztor", "depth", "Rhypo")
cnames.AM09 <- c("Mag", "Rrup", "Prd")
cnames.Arroyo2010 <- c("Mag", "Rrup", "Prd")
cnames.ASB14 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30")
cnames.ASB14.tw.B01 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30")
cnames.ASB14.tw.C01 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30")
cnames.ASB14.tw.E02 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30")
cnames.ASK14 <- c("Mag", "Rrup", "Rjb", "Prd", "Dip", "ftype", "rupwidth", "Vs30", "hwflag", "Ztor", "Vs30_class", "Z1.0", "Rx", "Ry0", "regionflag", "msasflag")
cnames.ASK14.tw.B01 <- c("Mag", "Rrup", "Rjb", "Prd", "Dip", "ftype", "rupwidth", "Vs30", "hwflag", "Ztor", "Vs30_class", "Z1.0", "Rx", "Ry0", "regionflag", "msasflag")
cnames.ASK14.tw.C01 <- c("Mag", "Rrup", "Rjb", "Prd", "Dip", "ftype", "rupwidth", "Vs30", "hwflag", "Ztor", "Vs30_class", "Z1.0", "Rx", "Ry0", "regionflag", "msasflag")
cnames.ASK14.tw.E03 <- c("Mag", "Rrup", "Rjb", "Prd", "Dip", "ftype", "rupwidth", "Vs30", "hwflag", "Ztor", "Vs30_class", "Z1.0", "Rx", "Ry0", "regionflag", "msasflag")
cnames.BCHydroSubV3 <- c("Mag", "ftype", "Rrup", "Vs30", "Prd", "forearc", "depth", "Rhypo")
cnames.BI14 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30")
cnames.BI14.tw.B01 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30")
cnames.BI14.tw.C01 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30")
cnames.BI14.tw.E02 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30")
cnames.BSSA14 <- c("Mag", "Rjb", "Prd", "Vs30", "ftype", "Z1.0", "regionflag", "basinflag")
cnames.BSSA14.tw.B01 <- c("Mag", "Rjb", "Prd", "Vs30", "ftype", "Z1.0", "regionflag", "basinflag")
cnames.BSSA14.tw.C01 <- c("Mag", "Rjb", "Prd", "Vs30", "ftype", "Z1.0", "regionflag", "basinflag")
cnames.BSSA14.tw.E02 <- c("Mag", "Rjb", "Prd", "Vs30", "ftype", "Z1.0", "regionflag", "basinflag")
cnames.Camp03H <- c("Mag", "Rjb", "Rseis", "Prd", "Svfs", "Ssr", "Sfr", "Frv", "Fth", "hwflag")
cnames.CB14 <- c("Mag", "Rrup", "Rjb", "ftype", "Prd", "Vs30", "Ztor", "Z2.5", "Dip", "depth", "hwflag", "Rx", "rupwidth", "regionflag")
cnames.CB14.tw.C01 <- c("Mag", "Rrup", "Rjb", "ftype", "Prd", "Vs30", "Ztor", "Z2.5", "Dip", "depth", "hwflag", "Rx", "rupwidth", "regionflag")
cnames.CB14.tw.E05 <- c("Mag", "Rrup", "Rjb", "ftype", "Prd", "Vs30", "Ztor", "Z2.5", "Dip", "depth", "hwflag", "Rx", "rupwidth", "regionflag")
cnames.Chao2017 <- c("Mag", "Rrup", "ftype", "Vs30_class", "Vs30", "Prd", "sourcetype", "Ztor", "Z1.0", "msasflag")
cnames.Chao2018 <- c("Mag", "Rrup", "ftype", "Vs30_class", "Vs30", "Prd", "sourcetype", "Ztor", "Z1.0", "msasflag")
cnames.Cru.Com.001 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.002 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.003 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.004 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.005 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.006 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.007 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.008 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.009 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.010 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.011 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.012 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.013 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.014 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.015 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.016 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.Cru.Com.017 <- c("Mag", "Rrup", "Rjb", "Ztor", "ftype", "Dip", "rupwidth", "Rx", "hwflag", "Prd")
cnames.CY08 <- c("Mag", "Rrup", "Rjb", "Prd", "Vs30", "Dip", "Ztor", "ftype", "Z1.0", "Vs30_class", "hwflag", "Rx", "regionflag")
cnames.CY14 <- c("Mag", "Rrup", "Rjb", "Prd", "Vs30", "Dip", "Ztor", "ftype", "Z1.0", "Vs30_class", "hwflag", "Rx", "regionflag")
cnames.CY14.tw.B01 <- c("Mag", "Rrup", "Rjb", "Prd", "Vs30", "Dip", "Ztor", "ftype", "Z1.0", "Vs30_class", "hwflag", "Rx", "regionflag")
cnames.CY14.tw.C01 <- c("Mag", "Rrup", "Rjb", "Prd", "Vs30", "Dip", "Ztor", "ftype", "Z1.0", "Vs30_class", "hwflag", "Rx", "regionflag")
cnames.CY14.tw.E04 <- c("Mag", "Rrup", "Rjb", "Prd", "Vs30", "Dip", "Ztor", "ftype", "Z1.0", "Vs30_class", "hwflag", "Rx", "regionflag")
cnames.Garcia05 <- c("Mag", "Rrup", "Prd", "depth")
cnames.GK16 <- c("Mag", "Rrup", "ftype", "Prd", "Vs30", "q0", "Z1.5")
cnames.Gregor06 <- c("Mag", "Rrup", "Prd", "Vs30")
cnames.I14 <- c("Mag", "Rrup", "Prd", "ftype", "Vs30")
cnames.I14.tw.B01 <- c("Mag", "Rrup", "Prd", "ftype", "Vs30")
cnames.I14.tw.C01 <- c("Mag", "Rrup", "Prd", "ftype", "Vs30")
cnames.I14.tw.E04 <- c("Mag", "Rrup", "Prd", "ftype", "Vs30", "Ztor")
cnames.KAAH15 <- c("Mag", "Rjb", "Prd", "ftype", "Vs30", "regionflag")
cnames.Kanno06 <- c("Mag", "Rrup", "Prd", "Vs30", "depth")
cnames.Lin09 <- c("Mag", "Rrup", "Rrd", "Vs30", "ftype")
cnames.Lin11Rock <- c("Mag", "Rrup", "Prd", "hwflag")
cnames.Lin11Soil <- c("Mag", "Rrup", "Prd", "hwflag")
cnames.LL08 <- c("Mag", "Rrup", "depth", "ftype", "Prd", "Vs30")
cnames.LL08.C02 <- c("Mag", "Rrup", "Ztor", "ftype", "Prd", "Vs30")
cnames.LL08Rock <- c("Mag", "Rrup", "depth", "ftype", "Prd")
cnames.LL08Soil <- c("Mag", "Rrup", "depth", "ftype", "Prd")
cnames.LL08.C02 <- c("Mag", "Rrup", "Ztor", "ftype", "Prd", "Vs30")
cnames.LL08.E04 <- c("Mag", "Rrup", "Ztor", "ftype", "Prd", "Vs30")
cnames.LL08.F04 <- c("Mag", "Rrup", "Ztor", "ftype", "Prd", "Vs30")
cnames.Loh96 <- c("Mag", "Rrup")
cnames.MBR17 <- c("Mag", "Rrup", "Prd", "ftype", "Vs30", "forearc", "depth", "Rhypo")
cnames.Mcverry2006Sub <- c("Mag", "Rrup", "Prd", "ftype", "Ztor", "Dip", "rupwidth", "depth", "Sc", "Sd")
cnames.PhungCru17 <- c("Mag", "Rrup", "Prd", "Vs30", "Dip", "Ztor", "ftype", "Z1.0", "Vs30_class", "msasflag", "regionflag")
cnames.PhungCru18 <- c("Mag", "Rrup", "Rjb", "Rx", "Prd", "Vs30", "Dip", "Ztor", "ftype", "Z1.0", "Vs30_class", "regionflag", "hwflag")
cnames.PhungSub17 <- c("Mag", "Rrup", "Prd", "ftype", "Vs30", "Z1.0", "Ztor", "regionflag")
cnames.PhungSub18 <- c("Mag", "Rrup", "Prd", "ftype", "Vs30", "Z1.0", "Ztor", "regionflag")
cnames.Sinotech12 <- c("Mag", "Rrup", "Rrd", "Vs30", "ftype")
cnames.Sub.Inter.Com.001 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.002 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.003 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.004 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.005 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.006 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.007 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.008 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.009 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.010 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.011 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.012 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.013 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.014 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.015 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.016 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Inter.Com.017 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.001 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.002 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.003 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.004 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.005 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.006 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.007 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.008 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.009 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.010 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.011 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.012 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.013 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.014 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.015 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.016 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Sub.Intra.Com.017 <- c("Mag", "Rrup", "Ztor", "Prd")
cnames.Youngs97Rock <- c("Mag", "Rrup", "Prd", "ftype", "depth")
cnames.Zh06 <- c("Mag", "Rrup", "ftype", "sclass", "Prd", "sourceclass", "depth")
cnames.Zh16Cru <- c("Mag", "Rrup", "ftype", "sclass", "Prd", "sourceclass", "depth")
cnames.Zh16Inter <- c("Mag", "Rrup", "sclass", "Prd", "depth")
cnames.Zh16Slab <- c("Mag", "Rrup", "sclass", "Prd", "depth")
cnames.Zh16Sub <- c("Mag", "Rrup", "sclass", "Prd", "sourceclass", "depth")
save(list=ls(pattern=("cname.*")), file="data/cnames.rda")
