C  ***** PEER NGA-West 2 MODELS (2013) **********
c ---------------------------------------------------------------------
C ** Idriss (NGA-2013) Horizontal **
C     PEER Report 2013/08
C        NGA-West2 Model for Estimating Average Horizontal Values of
C            Pseudo-Absolute Spectral Accelerations Generated by
C            Crustal Earthquakes
C         I. M. Idriss
C     Notes:
C        Applicable Range (see Abstract):
C           5 <= M <= 8.5
C           Vs>=450 m/sec
C              for Vs>1200 use Vs=1200
C           Rrup <= 150 km
C        Mechanisms: Strike-slip and Norml (0)
C                    Reverse and Oblique (1)
c ---------------------------------------------------------------------
      Subroutine I14_TW_C01 ( m, Rrup, ftype, vs30, specT,
     1                     period2, lnY, sigma, iflag )
C     Last Updated: 5/18/13
      implicit none
      integer MAXPER
      parameter (MAXPER=25)
      REAL Period(MAXPER), a1mlt675(MAXPER), a2mlt675(MAXPER), a3mlt675(MAXPER)
      REAL b1mlt675(MAXPER), b2mlt675(MAXPER)
      REAL a1(MAXPER), a2(MAXPER), a3(MAXPER), b1(MAXPER), b2(MAXPER)
      real gam(MAXPER), phi(MAXPER), xsi(MAXPER), period1
      REAL M, Rrup, Vs30, specT, sigma
      REAL SOF, period2, lnY, PhiT, gamT, XsiT, ftype
      real a1T, a2T, a3T, b1T, b2T, a1mlt675T, a2mlt675T, a3mlt675T, b1mlt675T, b2mlt675T
      integer iflag, count1, count2, nPer, i


      Data Period(1:25) / 0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.075, 0.1, 0.12, 0.15, 0.17, 0.2, 0.25, 0.3, 0.4, 0.5, 0.75, 1, 1.5, 2,
     1      3, 4, 5, 7.5, 10/
      Data a1mlt675(1:25) / 2.500233380713, 2.50558343921901, 2.54905389007533, 2.66315218302058, 3.0465390943314,
     1      3.41168122348334, 3.53305607116099, 4.21379608491631, 4.12227689763015, 3.72362656328493, 4.00303950423054,
     1      4.20873194310916, 3.95556883190431, 4.2483082536625, 4.06438168106831, 3.97839067786446, 3.2169039370047,
     1      2.03558750338934, 1.33122659044408, -0.185188948776329, -1.92219595865101, -2.75022102589597, -4.14418500864792,
     1      -5.36713918636102, -7.44125982871721/
      Data a2mlt675(1:25) / 0.501420705570071, 0.50045274486304, 0.49013841997293, 0.476630410483486, 0.364470577366067,
     1      0.260841471360512, 0.2614288686757, 0.220757752258636, 0.258514730282064, 0.334072823230007, 0.329265244826973,
     1      0.325192262976761, 0.350819255594322, 0.329717876309448, 0.379780263480321, 0.419759529827459, 0.603851798024095,
     1      0.856643686843613, 0.960706519770273, 1.14832767985058, 1.33436528125161, 1.29373670045768, 1.37441955857378,
     1      1.31373625595917, 1.41503742549729/
      Data a3mlt675(1:25) / 0.0589, 0.0589, 0.0589, 0.0589, 0.0492134623324272, 0.0417, 0.0527, 0.0442, 0.0391188387593093, 0.0329,
     1      0.0267654491028554, 0.0188, 0.0095, -0.0039, -0.0133, -0.0224, -0.0267, -0.0198, -0.0367, -0.0291, -0.0214, -0.024,
     1      -0.0202, -0.0219, -0.0035/
      Data b1mlt675(1:25) / 2.9935, 2.9935, 2.9935, 2.9935, 2.92192099200299, 2.8664, 2.9406, 3.019, 2.91472377949414, 2.7871,
     1      2.81929551534672, 2.8611, 2.8289, 2.8423, 2.83, 2.856, 2.7544, 2.7339, 2.68, 2.6837, 2.6907, 2.5782, 2.5468, 2.4478,
     1      2.3922/
      Data b2mlt675(1:25) / -0.2287, -0.2287, -0.2287, -0.2287, -0.236077537409605, -0.2418, -0.2513, -0.2516, -0.23900951196997,
     1      -0.2236, -0.223295447827801, -0.2229, -0.22, -0.2284, -0.2318, -0.2337, -0.2392, -0.2398, -0.2417, -0.245, -0.2389,
     1      -0.2514, -0.2541, -0.2593, -0.2586/
      Data xsi(1:25) / -0.418699682752246, -0.418615223959223, -0.410872380718745, -0.403366643966195, -0.390638638085288,
     1      -0.369589338311506, -0.343323354414622, -0.330917990949051, -0.349509622112699, -0.3645285353545, -0.383246394748638,
     1      -0.390867061900157, -0.393160229911773, -0.439607616873627, -0.50735066440335, -0.555860494660592, -0.750091656095736,
     1      -0.872310784811448, -0.967396910488233, -0.979257377149927, -0.987613564785966, -0.997568672611442, -0.953592248112969,
     1      -0.891337622105761, -0.794820984688996/
      Data gam(1:25) / -0.00283013920396674, -0.00282803033499828, -0.00290526852332255, -0.0035024282565208, -0.00571328650969498,
     1      -0.00758878173241265, -0.00846045072079165, -0.00769077769427285, -0.00776930447201177, -0.00738500857491979,
     1      -0.00628375110597102, -0.0046841295810579, -0.00346640983735254, -0.00322976125564237, -0.00218135066244653,
     1      -0.000916435063493218, -0.00195789280161822, -0.00282711858804776, -0.00364343441913228, -0.004785164050821,
     1      -0.00281482371882879, -0.00461977029165467, -0.00480352660804264, -0.00599454233673703, -0.0062195400597961/
      Data phi(1:25) / 0.200739641446067, 0.200813356085181, 0.199656078139181, 0.194723442703274, 0.18902048140083,
     1      0.182402028007246, 0.160818007837235, 0.155060599538377, 0.149501396019003, 0.147001197734822, 0.161553742915627,
     1      0.1945576588434, 0.215937776551892, 0.216160624099592, 0.239974142176991, 0.257520562672612, 0.277554637391253,
     1      0.297363818562307, 0.276583423687761, 0.256719938372776, 0.180567884489731, 0.0750113965684316, 0.0606074683089297,
     1      -0.107929819900768, -0.121318376812063/
      Data a1(1:25) / 9.0138, 9.0408, 9.1338, 8.48609726910026, 7.9837, 7.756, 9.4252, 9.51468239707057, 9.6242, 10.2793352298525,
     1      11.13, 11.3629, 11.7818, 11.6097, 11.4484, 10.9065, 9.8565, 8.3363, 6.8656, 4.1178, 1.8102, 0.0977, -3.0563, -4.4387,
     1      9.0138/
      Data a2(1:25) / -0.0794, -0.0794, -0.0794, -0.0794, -0.142981982713312, -0.1923, -0.1614, -0.1887, -0.133751512954654,
     1      -0.0665, -0.111443199125889, -0.1698, -0.1766, -0.2798, -0.3048, -0.2911, -0.3097, -0.2565, -0.232, -0.1226, 0.1724,
     1      0.3001, 0.4609, 0.6948, 0.8393/
      Data a3(1:25) / 0.0589, 0.0589, 0.0589, 0.0589, 0.0492134623324272, 0.0417, 0.0527, 0.0442, 0.0391188387593093, 0.0329,
     1      0.0267654491028554, 0.0188, 0.0095, -0.0039, -0.0133, -0.0224, -0.0267, -0.0198, -0.0367, -0.0291, -0.0214, -0.024,
     1      -0.0202, -0.0219, -0.0035/
      Data b1(1:25) / 2.9935, 2.9935, 2.9935, 2.9935, 2.88424486584249, 2.7995, 2.8143, 2.8131, 2.63143724413814, 2.4091,
     1      2.44595081283604, 2.4938, 2.3773, 2.3772, 2.3413, 2.3477, 2.2042, 2.1493, 2.0408, 2.0013, 1.9408, 1.7763, 1.703,
     1      1.5212, 1.4195/
      Data b2(1:25) / -0.2287, -0.2287, -0.2287, -0.2287, -0.230502146542804, -0.2319, -0.2326, -0.2211, -0.197043174656907,
     1      -0.1676, -0.167991567078541, -0.1685, -0.1531, -0.1595, -0.1594, -0.1584, -0.1577, -0.1532, -0.147, -0.1439, -0.1278,
     1      -0.1326, -0.1291, -0.122, -0.1145/


C Find the requested spectral period and corresponding coefficients
      nPer = 25
C First check for the PGA case (i.e., specT=0.0)
      if (specT .eq. 0.0) then
         period1 = period(1)
         a1T     = a1(1)
         a2T     = a2(1)
         a3T     = a3(1)
         b1T     = b1(1)
         b2T     = b2(1)
         a1mlt675T = a1mlt675(1)
         a2mlt675T = a2mlt675(1)
         a3mlt675T = a3mlt675(1)
         b1mlt675T = b1mlt675(1)
         b2mlt675T = b2mlt675(1)
         xsiT   = xsi(1)
         gamT   = gam(1)
         phiT   = phi(1)
         goto 1011
      elseif (specT .gt. 0.0) then
C Now loop over the spectral period range of the attenuation relationship.
         do i=2,nper-1
            if (specT .ge. period(i) .and. specT .le. period(i+1) ) then
               count1 = i
               count2 = i+1
               goto 1020
            endif
         enddo
      endif
C Selected spectral period is outside range defined by attenuaton model.
      write (*,*)
      write (*,*) 'Idriss (NGA West2-2013) Horizontal'
      write (*,*) 'attenuation model is not defined for a '
      write (*,*) ' spectral period of: '
      write (*,'(a10,f10.5)') ' Period = ',specT
      write (*,*) 'This spectral period is outside the defined'
      write (*,*) 'period range in the code or beyond the range'
      write (*,*) 'of spectral periods for interpolation.'
      write (*,*) 'Please check the input file.'
      write (*,*)
      stop 99
C Interpolate the coefficients for the requested spectral period.
 1020       call interp (period(count1),period(count2),a1(count1),a1(count2),
     +                   specT,a1T,iflag)
            call interp (period(count1),period(count2),a2(count1),a2(count2),
     +                   specT,a2T,iflag)
            call interp (period(count1),period(count2),a3(count1),a3(count2),
     +                   specT,a3T,iflag)
            call interp (period(count1),period(count2),b1(count1),b1(count2),
     +                   specT,b1T,iflag)
            call interp (period(count1),period(count2),b2(count1),b2(count2),
     +                   specT,b2T,iflag)
            call interp (period(count1),period(count2),a1mlt675(count1),a1mlt675(count2),
     +                   specT,a1mlt675T,iflag)
            call interp (period(count1),period(count2),a2mlt675(count1),a2mlt675(count2),
     +                   specT,a2mlt675T,iflag)
            call interp (period(count1),period(count2),a3mlt675(count1),a3mlt675(count2),
     +                   specT,a3mlt675T,iflag)
            call interp (period(count1),period(count2),b1mlt675(count1),b1mlt675(count2),
     +                   specT,b1mlt675T,iflag)
            call interp (period(count1),period(count2),b2mlt675(count1),b2mlt675(count2),
     +                   specT,b2mlt675T,iflag)
            call interp (period(count1),period(count2),phi(count1),phi(count2),
     +                   specT,phiT,iflag)
            call interp (period(count1),period(count2),gam(count1),gam(count2),
     +                   specT,gamT,iflag)
            call interp (period(count1),period(count2),xsi(count1),xsi(count2),
     +                   specT,xsiT,iflag)
 1011 period1 = specT
C.....Compute the Ground motion.......
C.....Set the mechanism term.....................
C     Strike-slip and normal events --> SOF = 0
C     Reverse and oblique events     --> SOF = 1
C     Otherwise assume SOF = 0
      if (ftype .gt. 0.0) then
         SOF = 1.0
      else
         SOF = 0.0
      endif

	  a1T = a1mlt675T + (a2mlt675T - a2T) * 6.75

      if (m .le. 6.75) then
         lnY = a1mlt675T + a2mlt675T*m + a3mlt675T*(8.5 - m)**2.0 - (b1mlt675T+b2mlt675T*m) * alog(Rrup+10.0) +
     1         xsiT*alog(Vs30) + gamT*rRup + SOF*phiT
      else
         lnY = a1T + a2T*m + a3T*(8.5 - m)**2.0 - (b1T+b2T*m) * alog(Rrup+10.0) +
     1         xsiT*alog(Vs30) + gamT*rRup + SOF*phiT
      endif
C     Convert ground motion to units of gals.
      lnY = lnY + 6.89
C     Compute Sigma which is Period and magnitude dependent.
C     Note report does not state a limit on sigma for M<5 but
C     Since model is only applicable for M>=5 a limit is retained
C     for sigma with M<5 equal to M=5 values.
      if (specT .le. 0.05) then
         if (m .le. 5.0) then
            sigma = 1.18 + 0.035*alog(0.05) - 0.06*5.0
         elseif (m .ge. 7.5) then
            sigma = 1.18 + 0.035*alog(0.05) - 0.06*7.5
         else
            sigma = 1.18 + 0.035*alog(0.05) - 0.06*m
         endif
      elseif (specT .ge. 3.0) then
         if (m .le. 5.0) then
            sigma = 1.18 + 0.035*alog(3.00) - 0.06*5.0
         elseif (m .ge. 7.5) then
            sigma = 1.18 + 0.035*alog(3.00) - 0.06*7.5
         else
            sigma = 1.18 + 0.035*alog(3.00) - 0.06*m
         endif
      else
         if (m .le. 5.0) then
            sigma = 1.18 + 0.035*alog(specT) - 0.06*5.0
         elseif (m .ge. 7.5) then
            sigma = 1.18 + 0.035*alog(specT) - 0.06*7.5
         else
            sigma = 1.18 + 0.035*alog(specT) - 0.06*m
         endif
      endif
      period2 = period1
      return
      end


c ---------------------------------------------------------------------
C ** Idriss (NGA-2013) Horizontal **
C     PEER Report 2013/08
C        NGA-West2 Model for Estimating Average Horizontal Values of
C            Pseudo-Absolute Spectral Accelerations Generated by
C            Crustal Earthquakes
C         I. M. Idriss
C     Notes:
C        Applicable Range (see Abstract):
C           5 <= M <= 8.5
C           Vs>=450 m/sec
C              for Vs>1200 use Vs=1200
C           Rrup <= 150 km
C        Mechanisms: Strike-slip and Norml (0)
C                    Reverse and Oblique (1)
c ---------------------------------------------------------------------
      Subroutine I14_TW_B01 ( m, Rrup, ftype, vs30, specT,
     1                     period2, lnY, sigma, iflag )

C     Last Updated: 5/18/13

      implicit none

      integer MAXPER
      parameter (MAXPER=25)
      REAL Period(MAXPER), a1mlt675(MAXPER), a2mlt675(MAXPER), a3mlt675(MAXPER)
      REAL b1mlt675(MAXPER), b2mlt675(MAXPER)
      REAL a1(MAXPER), a2(MAXPER), a3(MAXPER), b1(MAXPER), b2(MAXPER)
      real gam(MAXPER), phi(MAXPER), xsi(MAXPER), period1

      REAL M, Rrup, Vs30, specT, sigma
      REAL SOF, period2, lnY, PhiT, gamT, XsiT, ftype

      real a1T, a2T, a3T, b1T, b2T, a1mlt675T, a2mlt675T, a3mlt675T, b1mlt675T, b2mlt675T
      integer iflag, count1, count2, nPer, i

      Data Period / 0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.075, 0.1, 0.12, 0.15, 0.17, 0.2, 0.25, 0.3, 0.4, 0.5, 0.75, 1, 1.5, 2, 3, 4,
     1      5, 7.5, 10/
      Data a1mlt675 / 2.52717160622891, 2.53234425798523, 2.57009563882438, 2.64348244049103, 2.96390206180402, 3.28063158557095,
     1      3.36397158262202, 4.16247647949706, 4.11037653533263, 3.7910964029315, 4.09440601055076, 4.32570942349766,
     1      4.18827278322137, 4.51231841039853, 4.3497169606023, 4.25776196853824, 3.56061505213009, 2.46466483649309,
     1      1.91631584881243, 0.439690835121291, -1.25103903611714, -2.11714556942583, -3.51887081562755, -4.79113307280219,
     1      -6.89391327951502/
      Data a2mlt675 / 0.460312671375271, 0.459405267637648, 0.448879735050439, 0.434062498502365, 0.321778345213789,
     1      0.217082211958214, 0.217955862935735, 0.177038021760217, 0.213032953920886, 0.288055385973761, 0.279940285807971,
     1      0.276944578377992, 0.306499165667397, 0.290922802609074, 0.350863102110982, 0.394077574831295, 0.575107425986237,
     1      0.820077695671963, 0.915580192283733, 1.08926214360982, 1.25355703117415, 1.19040821139199, 1.25930202906491,
     1      1.19688590523688, 1.30080116276695/
      Data a3mlt675 / 0.0589, 0.0589, 0.0589, 0.0589, 0.0492134623324272, 0.0417, 0.0527, 0.0442, 0.0391188387593093, 0.0329,
     1      0.0267654491028554, 0.0188, 0.0095, -0.0039, -0.0133, -0.0224, -0.0267, -0.0198, -0.0367, -0.0291, -0.0214, -0.024,
     1      -0.0202, -0.0219, -0.0035/
      Data b1mlt675 / 2.9935, 2.9935, 2.9935, 2.9935, 2.92192099200299, 2.8664, 2.9406, 3.019, 2.91472377949414, 2.7871,
     1      2.81929551534672, 2.8611, 2.8289, 2.8423, 2.83, 2.856, 2.7544, 2.7339, 2.68, 2.6837, 2.6907, 2.5782, 2.5468, 2.4478,
     1      2.3922/
      Data b2mlt675 / -0.2287, -0.2287, -0.2287, -0.2287, -0.236077537409605, -0.2418, -0.2513, -0.2516, -0.23900951196997,
     1      -0.2236, -0.223295447827801, -0.2229, -0.22, -0.2284, -0.2318, -0.2337, -0.2392, -0.2398, -0.2417, -0.245, -0.2389,
     1      -0.2514, -0.2541, -0.2593, -0.2586/
      Data xsi / -0.40369717245562, -0.403622508356977, -0.394835992368106, -0.379338783879813, -0.356178966894812,
     1      -0.326544254243393, -0.295817444297612, -0.305192740774835, -0.32883171799589, -0.355084382346931, -0.373179047923669,
     1      -0.382702508916895, -0.404009611502278, -0.460813853407414, -0.541103541075086, -0.589823372166685, -0.794504321991067,
     1      -0.927321127797923, -1.04255454844748, -1.05931107493644, -1.05428507087214, -1.03691569006648, -0.982507883713497,
     1      -0.911099829354897, -0.816328263721024/
      Data gam / -0.00182694393153657, -0.00182555365089912, -0.00189697322268273, -0.00248961208982924, -0.00468150197770854,
     1      -0.00651925229669866, -0.00732868905481044, -0.00639515146785928, -0.00645085904170326, -0.00615781785031355,
     1      -0.00510664429780638, -0.00363507026324227, -0.00259152092598255, -0.00238590912005334, -0.00145036804656299,
     1      -0.000318332503439458, -0.0013004693235856, -0.00202453505278977, -0.00267998227908399, -0.00317683458362822,
     1      -0.00117099933099693, -0.00289731810890383, -0.00286186803467579, -0.00384618932840495, -0.0039363375626295/
      Data phi / 0.215270979717315, 0.215317172263311, 0.215115405478767, 0.213665416241352, 0.210959869133158, 0.206343489225473,
     1      0.187847727359729, 0.173885264080127, 0.167406231022477, 0.160773684163234, 0.170558946425175, 0.196244092994068,
     1      0.215411900150502, 0.215633575575745, 0.243078347711887, 0.259782846355648, 0.280669544145687, 0.303352249897888,
     1      0.273461339948178, 0.244844582664493, 0.179658901559622, 0.0879225310576709, 0.103931838361066, -0.0411424501970152,
     1      -0.0199216949439069/
      Data a1 / 9.0138, 9.0138, 9.0408, 9.1338, 8.48609726910026, 7.9837, 7.756, 9.4252, 9.51468239707057, 9.6242,
     1      10.2793352298525, 11.13, 11.3629, 11.7818, 11.6097, 11.4484, 10.9065, 9.8565, 8.3363, 6.8656, 4.1178, 1.8102, 0.0977,
     1      -3.0563, -4.4387/
      Data a2 / -0.0794, -0.0794, -0.0794, -0.0794, -0.142981982713312, -0.1923, -0.1614, -0.1887, -0.133751512954654, -0.0665,
     1      -0.111443199125889, -0.1698, -0.1766, -0.2798, -0.3048, -0.2911, -0.3097, -0.2565, -0.232, -0.1226, 0.1724, 0.3001,
     1      0.4609, 0.6948, 0.8393/
      Data a3 / 0.0589, 0.0589, 0.0589, 0.0589, 0.0492134623324272, 0.0417, 0.0527, 0.0442, 0.0391188387593093, 0.0329,
     1      0.0267654491028554, 0.0188, 0.0095, -0.0039, -0.0133, -0.0224, -0.0267, -0.0198, -0.0367, -0.0291, -0.0214, -0.024,
     1      -0.0202, -0.0219, -0.0035/
      Data b1 / 2.9935, 2.9935, 2.9935, 2.9935, 2.88424486584249, 2.7995, 2.8143, 2.8131, 2.63143724413814, 2.4091,
     1      2.44595081283604, 2.4938, 2.3773, 2.3772, 2.3413, 2.3477, 2.2042, 2.1493, 2.0408, 2.0013, 1.9408, 1.7763, 1.703,
     1      1.5212, 1.4195/
      Data b2 / -0.2287, -0.2287, -0.2287, -0.2287, -0.230502146542804, -0.2319, -0.2326, -0.2211, -0.197043174656907, -0.1676,
     1      -0.167991567078541, -0.1685, -0.1531, -0.1595, -0.1594, -0.1584, -0.1577, -0.1532, -0.147, -0.1439, -0.1278, -0.1326,
     1      -0.1291, -0.122, -0.1145/


C Find the requested spectral period and corresponding coefficients
      nPer = 25
C First check for the PGA case (i.e., specT=0.0)
      if (specT .eq. 0.0) then
         period1 = period(1)
         a1T     = a1(1)
         a2T     = a2(1)
         a3T     = a3(1)
         b1T     = b1(1)
         b2T     = b2(1)
         a1mlt675T = a1mlt675(1)
         a2mlt675T = a2mlt675(1)
         a3mlt675T = a3mlt675(1)
         b1mlt675T = b1mlt675(1)
         b2mlt675T = b2mlt675(1)
         xsiT   = xsi(1)
         gamT   = gam(1)
         phiT   = phi(1)
         goto 1011
      elseif (specT .gt. 0.0) then
C Now loop over the spectral period range of the attenuation relationship.
         do i=2,nper-1
            if (specT .ge. period(i) .and. specT .le. period(i+1) ) then
               count1 = i
               count2 = i+1
               goto 1020
            endif
         enddo
      endif

C Selected spectral period is outside range defined by attenuaton model.
      write (*,*)
      write (*,*) 'Idriss (NGA West2-2013) Horizontal'
      write (*,*) 'attenuation model is not defined for a '
      write (*,*) ' spectral period of: '
      write (*,'(a10,f10.5)') ' Period = ',specT
      write (*,*) 'This spectral period is outside the defined'
      write (*,*) 'period range in the code or beyond the range'
      write (*,*) 'of spectral periods for interpolation.'
      write (*,*) 'Please check the input file.'
      write (*,*)
      stop 99

C Interpolate the coefficients for the requested spectral period.
 1020       call interp (period(count1),period(count2),a1(count1),a1(count2),
     +                   specT,a1T,iflag)
            call interp (period(count1),period(count2),a2(count1),a2(count2),
     +                   specT,a2T,iflag)
            call interp (period(count1),period(count2),a3(count1),a3(count2),
     +                   specT,a3T,iflag)
            call interp (period(count1),period(count2),b1(count1),b1(count2),
     +                   specT,b1T,iflag)
            call interp (period(count1),period(count2),b2(count1),b2(count2),
     +                   specT,b2T,iflag)
            call interp (period(count1),period(count2),a1mlt675(count1),a1mlt675(count2),
     +                   specT,a1mlt675T,iflag)
            call interp (period(count1),period(count2),a2mlt675(count1),a2mlt675(count2),
     +                   specT,a2mlt675T,iflag)
            call interp (period(count1),period(count2),a3mlt675(count1),a3mlt675(count2),
     +                   specT,a3mlt675T,iflag)
            call interp (period(count1),period(count2),b1mlt675(count1),b1mlt675(count2),
     +                   specT,b1mlt675T,iflag)
            call interp (period(count1),period(count2),b2mlt675(count1),b2mlt675(count2),
     +                   specT,b2mlt675T,iflag)
            call interp (period(count1),period(count2),phi(count1),phi(count2),
     +                   specT,phiT,iflag)
            call interp (period(count1),period(count2),gam(count1),gam(count2),
     +                   specT,gamT,iflag)
            call interp (period(count1),period(count2),xsi(count1),xsi(count2),
     +                   specT,xsiT,iflag)

 1011 period1 = specT

C.....Compute the Ground motion.......

C.....Set the mechanism term.....................
C     Strike-slip and normal events --> SOF = 0
C     Reverse and oblique events     --> SOF = 1
C     Otherwise assume SOF = 0
      if (ftype .gt. 0.0) then
         SOF = 1.0
      else
         SOF = 0.0
      endif

	  a1T = a1mlt675T + (a2mlt675T - a2T) * 6.75

      if (m .lt. 6.75) then
         lnY = a1mlt675T + a2mlt675T*m + a3mlt675T*(8.5 - m)**2.0 - (b1mlt675T+b2mlt675T*m) * alog(Rrup+10.0) +
     1         xsiT*alog(Vs30) + gamT*rRup + SOF*phiT
      else
         lnY = a1T + a2T*m + a3T*(8.5 - m)**2.0 - (b1T+b2T*m) * alog(Rrup+10.0) +
     1         xsiT*alog(Vs30) + gamT*rRup + SOF*phiT
      endif

C     Convert ground motion to units of gals.
      lnY = lnY + 6.89

C     Compute Sigma which is Period and magnitude dependent.
C     Note report does not state a limit on sigma for M<5 but
C     Since model is only applicable for M>=5 a limit is retained
C     for sigma with M<5 equal to M=5 values.
      if (specT .le. 0.05) then
         if (m .le. 5.0) then
            sigma = 1.18 + 0.035*alog(0.05) - 0.06*5.0
         elseif (m .ge. 7.5) then
            sigma = 1.18 + 0.035*alog(0.05) - 0.06*7.5
         else
            sigma = 1.18 + 0.035*alog(0.05) - 0.06*m
         endif
      elseif (specT .ge. 3.0) then
         if (m .le. 5.0) then
            sigma = 1.18 + 0.035*alog(3.00) - 0.06*5.0
         elseif (m .ge. 7.5) then
            sigma = 1.18 + 0.035*alog(3.00) - 0.06*7.5
         else
            sigma = 1.18 + 0.035*alog(3.00) - 0.06*m
         endif
      else
         if (m .le. 5.0) then
            sigma = 1.18 + 0.035*alog(specT) - 0.06*5.0
         elseif (m .ge. 7.5) then
            sigma = 1.18 + 0.035*alog(specT) - 0.06*7.5
         else
            sigma = 1.18 + 0.035*alog(specT) - 0.06*m
         endif
      endif

      period2 = period1

      return
      end