# ---- !! not finished ----
GMPE <- function(Mag=6.0, Rrup=10, Rjb=10, Rseis=10, Rhypo=10,
                 jcalc=8797, period=0.00, lnY=0.0, Sigma=0.65, tau=0.0, phi=0.0,
                 Vs30=1130, Depth=10, Vs30_class=0, hwflag=0, ftype=0,
                 attenName="GMPE", period1=matrix(as.single(0), 4, 3),
                 iAtten=0, iProb=0, jType=0, intflag=matrix(as.single(0), 4, 3), AR=0, Dip=0.0,
                 Z10=30, Z15=50, Z25=100, Ztor=0, Theta_Site=0,Width=50, foreArc=0, Rx=0.0,
                 Ry=0.0, cfcoefrrup=matrix(as.single(0), 40, 11), cfcoefrjb=matrix(as.single(0), 40, 11)){
  retvals <- .Fortran("meanInten",
                      rupdist=as.single(Rrup),
                      jbdist=as.single(Rjb),
                      seismodist=as.single(Rseis),
                      hwflag=as.integer(hwflag),
                      mag=as.single(Mag),
                      jcalc=as.integer(jcalc),
                      specT=as.single(period),
                      lnY=as.single(0.1),
                      siga=as.single(Sigma),
                      ftype=as.single(ftype),
                      attenName=attenName,
                      period1=period1,
                      iAtten=as.integer(iAtten),
                      iProb=as.integer(iProb),
                      jType=as.integer(jType),
                      vs=as.single(Vs30),
                      depth=as.single(Depth),
                      intflag=intflag,
                      AR=as.single(AR),
                      dip1=as.single(Dip),
                      disthypo=as.single(Rhypo),
                      depthvs10=as.single(Z10),
                      depthvs15=as.single(Z15),
                      D25=as.single(Z25),
                      tau=as.single(tau),
                      depthTop=as.single(Ztor),
                      Theta_Site=as.single(Theta_Site),
                      RupWidth=as.single(Width),
                      vs30_class=as.single(Vs30_class),
                      foreArc=as.integer(foreArc),
                      Rx=as.single(Rx),
                      phi=as.single(phi),
                      cfcoefrrup=cfcoefrrup,
                      cfcoefrjb=cfcoefrjb,
                      Ry0=as.single(Ry))
  return(retvals)
}
