#' GMPE function for Idriss(2014)
#'
#' \code{I14.tw.C01} returns the ground-motion prediction with it sigma of Idriss, I. M. (2014) GMPE
#' adjusted to Taiwan.
#'
#'Idriss, I. M. (2014). An NGA-West2 Empirical Model for Estimating the Horizontal
#'Spectral Values Generated by Shallow Crustal Earthquakes.
#'Earthquake Spectra, 30(3), 1155-1177.
#'\url{http://doi.org/10.1193/070613EQS195M}
#'     Notes:
#'     Applicable Range (see Abstract):
#'          5 <= M <= 8.5
#'          Vs>=450 m/sec
#'             for Vs>1200 use Vs=1200
#'          Rrup <= 150 km
#'     Mechanisms: Strike-slip and Norml (0)
#'                 Reverse and Oblique (1)
#'
#' @param Mag Earthquake momnet magnitude, Numeric.
#' @param Rrup Rupture distance(km), Numeric.
#' @param Prd Period of spectral acceleration.
#' @param ftype style of faulting.
#' @param Vs30 Vs30(m/s).
#'
#' @return A list will be return, including mag, Rrup, ftype, Vs30, specT, period, lnY, sigma, iflag.
#'
#' @examples
#' I14.tw.C01(6, 20, 0, 0, 760)
#' I14.tw.C01(7, 10, 0, 0, 760)
#'
#' @export
I14.tw.C01 <- function(Mag, Rrup, Prd=0, ftype=0, Vs30=760){
  #Subroutine I_NGAWest2_2013 ( m, Rrup, ftype, vs30, specT,
  #                     period2, lnY, sigma, iflag )
  if (Prd != 0 & (Prd < 0.01 | Prd > 10)) {
    stop("Period out of range! \n\n")
  }
  if (Vs30 >1200) Vs30 <- 1200
  retvals <- .Fortran("I14_TW_C01", m=as.single(Mag), Rrup=as.single(Rrup), ftype=as.single(ftype),
                      vs30=as.single(Vs30), specT=as.single(Prd), period2=as.single(0),
                      lnY=as.single(0.1), sigma=as.single(0.1), iflag=as.integer(0))
  names(retvals) <- c("mag", "Rrup", "ftype", "Vs30","specT", "period", "lnY", "sigma", "iflag")
  return(retvals)
}
